skynet:
  service-list:
    data-resource-repository:
      url: http://resource-repository
    robot-factory:
      url: http://robot-factory
    user:
      url: http://user
    rank-league:
      url: http://rank-league
    battle:
      url: http://battle